### ISSUE TITLE
Additional area metadata to include parkings, trail heads coordinates and approach trails

### ISSUE THREAD

**Issue by vnugent** [OpenBeta/open-tacos#1101]
**What would you like to be able to do? Please describe.**
Currently we have a free-text description for an area and its latitude/longitude (which only makes sense for a small crag).
As a user I want have more detailed information such coordinates of parking lots and/or trailheads as well as approach trail GPX.

**How important is this to you** (Please pick one)
- Important

### Proposed GIS metadata for an area
```yaml
parkings: # can have 1 or more entries
- name: P1
  description: Trail head parking lot # optional field
  coordinates: [lat, lng] # required field
- name: Visitor center Parking 2
  coordinates: [lat2, lng2]
  description: 

trails:
 - name: Approach trail 1
   gpx: <data structure> # TBD
```

Related issues
- https://github.com/OpenBeta/open-tacos/issues/1051
- https://github.com/OpenBeta/open-tacos/issues/1057

**Comment by UvixCreative** [comment]
Personally, I would vote that a trail be either link or ID for a "way" or trail in OSM, as opposed to GPX data. I feel like full-on map data for trails is outside the scope of OpenBeta as an application, and as a result it would be lacking in terms of end-user experience due to lack of good data.

However, I do really like the idea of having a field for parking lots or trailheads.

I'd love this to have a dedicated schema (partly for searchability and partly to prompt contributors to link this data), but I would argue this is a relatively low-priority feature request. Reason being that using markdown for descriptions already allows a contributor to organize the description into multiple sections, including a section for access descriptions/links (the way I did [here](https://openbeta.io/area/f6615b22-36be-5cdd-ade3-9e763f8baaba/c-section))

**Comment by hcars** [comment]
@vnugent I'm interested in taking a stab at adding the parking areas. Is anyone else already working this issue? In addition, to the lat, long fields I think that adding an optional photo pairing would be helpful as well as cost of parking.

```
parkings: # can have 1 or more entries
- name: P1
  description: Trail head parking lot # optional field
  cost: $ amount # required field, default to free
  photo: # optional field
  coordinates: [lat, lng] # required field
- name: Visitor center Parking 2
  coordinates: [lat2, lng2]
  cost: $ amount # required field, default to free
  photo: # optional field
  description: 
```
